# Sensor plots

This section works but am waiting on grab sample data from RMRS to make correlation plots between grab sample and lab data
## Time series sensor data
```{r}
source("paper_analysis/functions/build_ts_plot.R")

# sites <- c("JOEI", "CBRI", "CHD")
# param_oi <- filter(sensor_meta, sensor_meta$key_param == TRUE)%>%
#   pull(param_common)
# 
# combinations <- expand.grid(site_name = c("JOEI", "CBRI", "CHD"), param = param_oi)
# 
# # Use pmap to apply the function to each combination
# plots_list <- pmap(combinations, build_ts_plot)

      chd_chla <- build_ts_plot(site_name = "chd", param = "chla", color = "#00946c", grabs = TRUE)+
       theme(axis.title.x = element_blank())+
         labs(title = "Site: Chambers Outflow (CHD)")
   chd_depth <-build_ts_plot(site_name = "chd",param = "depth",  color = "#0072B2", grabs = TRUE)
   ggarrange(chd_chla,chd_depth,  nrow = 2, ncol = 1)
   ggsave(filename = "data/figs_output/2023_figs/chla_depth_chd.jpg", width = 12, height = 10,  dpi = 300)
   
#     cbri_chla <- build_ts_plot(site_name = "cbri", param = "chla", color = "#00946c")+
#      theme(axis.title.x = element_blank())+
#       labs(title = "Joe Wright Outflow/Chambers Inflow")
#     #       axis.title.y = element_blank())
#   cbri_depth <-build_ts_plot(param = "depth", site_name = "cbri", color = "#0072B2")
#   
#   ggarrange(cbri_chla, chd_chla, cbri_depth,chd_depth,  nrow = 2, ncol = 2)
#   #ggsave("test_fig/chla_depth_cbri_chd.jpg", dpi = 300, width = 12, height = 8)
#   
#       joei_chla <- build_ts_plot(site_name = "joei", param = "chla", color = "#00946c")+
#     theme(axis.title.x = element_blank())
#   joei_depth <-build_ts_plot(site_name = "joei",param = "depth",  color = "#0072B2")
#   
#   
#     ggarrange(chd_chla, chd_depth, nrow = 2)
#   #ggsave("test_fig/chla_depth_chd.jpg", dpi = 300)
#   
#   
#   
#    ggarrange(joei_chla, cbri_chla,chd_chla, joei_depth, cbri_depth,chd_depth, nrow = 2, ncol = 3)
#   #ggsave("test_fig/chla_depth_jw_long.jpg", dpi = 300)
#   
#    
#    
#    pbd_turb_grabs <- build_ts_plot(site_name = "pbd", param = "turb", color = "#85722b", start_dt = "2023-07-23 00:00", end_dt = "2023-09-15 00:00", grabs = TRUE)+
#      ylim(0,1000)

 # ggsave("test_fig/turb_pbd_grabs_0809.jpg", dpi = 300, width = 8, height = 6)
```
## Correlate grab and sensor data

```{r}
source("paper_analysis/functions/correlate_grab_sensor.R")

hourly_corr <- correlate_grab_sonde_df(timestep = "1hour")%>%
  mutate(campaign = case_when(site %in% c( "lincoln", "timberline", "prospect", "archery", "boxcreek", "boxelder") ~ "lower", 
                              TRUE ~ "upper"))%>%
  select(site, grab_dt,campaign, everything())
inst_corr <- correlate_grab_sonde_df(timestep = "15min")%>%
  mutate(campaign = case_when(site %in% c( "lincoln", "timberline", "prospect", "archery", "boxcreek", "boxelder") ~ "lower", 
                              TRUE ~ "upper"))%>%
  select(site, grab_dt,campaign, everything())
daily_corr <- correlate_grab_sonde_df(timestep = "1day")%>%
  mutate(campaign = case_when(site %in% c( "lincoln", "timberline", "prospect", "archery", "boxcreek", "boxelder") ~ "lower", 
                              TRUE ~ "upper"))%>%
  select(site, grab_dt,campaign, everything())

hourly_corr$site = factor(hourly_corr$site, levels = c("joei", "cbri", "chd", "sfm", "pbd", "lincoln", "timberline", "prospect", "boxelder", "boxcreek", "archery"))
inst_corr$site = factor(inst_corr$site, levels = c("joei", "cbri", "chd", "sfm", "pbd", "lincoln", "timberline", "prospect", "boxelder", "boxcreek", "archery"))
daily_corr$site = factor(daily_corr$site, levels = c("joei", "cbri", "chd", "sfm", "pbd", "lincoln", "timberline", "prospect", "boxelder", "boxcreek", "archery"))
inst_corr$campaign = factor(inst_corr$campaign, levels = c("upper", "lower"))
hourly_corr$campaign = factor(hourly_corr$campaign, levels = c("upper", "lower"))
daily_corr$campaign = factor(daily_corr$campaign, levels = c("upper", "lower"))

```

## Plot all data
### Function
```{r}

or_colors <-c( "#01377D", "#009DD1", "#97E7F5", "#7ED348", "#26B170", "#F5E15A", "#F4BE1D", "#FEA305", "#F26021", "purple")

sensor_params <- sensor_meta%>%
  filter(key_param == TRUE)%>%
  mutate(param_sonde = case_when(param_sonde == "Turbidity" ~ "Turbidity_Sensor", 
                                 param_sonde == "pH" ~ "pH_sensor",
                                 TRUE ~ param_sonde))%>%
  pull(param_sonde)

all_combos <- crossing(chem_units$simple, sensor_params)%>%
  rename(lab_param = `chem_units$simple`,
         sensor_param = sensor_params)

plot_corr <- function(data, lab_param, sensor_param, matched_axes = FALSE, basesize = 28){
  
  
  plot <- data %>%
  ggplot(aes(x = .data[[lab_param]], y = .data[[sensor_param]]))+
  geom_point(aes(color = site, shape = campaign), size = 4)+
  #geom_smooth(method = "loess")+
  scale_color_manual(name = "Site", values = or_colors) +
  labs(x = paste0("Lab ", lab_param), y = paste0("Sensor ", sensor_param), shape = "Network")+
  # fix x axis to 7  to 9
  #xlim(0,3000)+
  # fix y axis to 7 to 9
  #ylim(0,3000)+
  #facet_wrap(~campaign, scales = "fixed")+
  theme_bw(base_size = basesize)
  # add one to one line
  
  if(matched_axes == TRUE){
    plot <- plot + geom_abline(intercept = 0, slope = 1, color = "black", linetype = "dashed")
  }
  
  return(plot)
  
}

```

## Generate plots
```{r}

hourly_corr_plots <- map2(all_combos$lab_param, all_combos$sensor_param, ~plot_corr(hourly_corr, .x, .y))%>%
  set_names(paste0(all_combos$lab_param, "_", all_combos$sensor_param))
daily_corr_plots <- map2(all_combos$lab_param, all_combos$sensor_param, ~plot_corr(daily_corr, .x, .y))%>%
  set_names(paste0(all_combos$lab_param, "_", all_combos$sensor_param))

```
## write datasets

```{r}

writexl::write_xlsx(x = hourly_corr, path = "data/sensor_data/correlations/hourly_corr.xlsx")
writexl::write_xlsx(x = daily_corr, path = "data/sensor_data/correlations/daily_corr.xlsx")
writexl::write_xlsx(x = inst_corr, path = "data/sensor_data/correlations/inst_corr.xlsx")
writexl::write_xlsx(x = sensor_meta, path = "data/sensor_data/correlations/meta_units.xlsx")
writexl::write_xlsx(x = chem_units, path = "data/sensor_data/correlations/chem_units.xlsx")

```

